tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: site_title
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Site Title'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 66
          -
            handle: site_logo
            field:
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Site Logo'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 33
              max_files: 1
              min_files: 1
